# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 050afc61abf138e82051f6d9baebe725db0fa25af0b4d6149f991fefcc93101ae2758e95d30f636565248076a78c446b1fd74d61b9eb41d7c5fe1a3253824f80
  stripe_secret_key: 'sk_test_gkEbrmaicohWPnWMTh6PU0Yt'
  stripe_publisher_key: 'pk_test_FSf0Jlc4OWieKatW06HNpt8m'

test:
  secret_key_base: 351b98204f036bb7fbf68123919d5d58806c70d94c7c59bb65c9d03b3e527bbdb911934d476b8e9d5ae9cb3e641f794fbc919c9434031df620963bc4a537351f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
